### ISSUE TITLE
Not a "template"

### ISSUE THREAD

**Issue by rwxrob** [lirantal/asciidoc-book-starter#7]
The following command fails because this repo is not actually a GitHub "template":

```
$ gh repo create blah --public --clone --template lirantal/asciidoc-book-starter
GraphQL: Could not clone: lirantal/asciidoc-book-starter is not a template repository. (cloneTemplateRepository)
```

As opposed to an _actual_ template:

```
$ gh repo create blah --public --clone --template rwxrob/bonzai-example
✓ Created repository rwxrob/blah on GitHub
Cloning into 'blah'...
```

**Comment by lirantal** [comment]
Ahh indeed, I didn't set this as a template repo. I'll see if I can update that. Thanks Rob.

**Comment by lmammino** [comment]
It's working now ;)

(BTW I was not aware of this handy `gh` command! Thx @rwxrob!)
